spring:
  application:
    name: vt-imt

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  sql:
    init:
      mode: always
      continue-on-error : true