name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t vt-imt-backend .

      - name: Save Docker image as artifact
        run: docker save vt-imt-backend | gzip > backend-image.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-image
          path: backend-image.tar.gz
